version: "3"
services:

        database:
                container_name: mailsenderDatabase
                image: postgres
                environment:
                        - POSTGRES_USER=postgres
                        - POSTGRES_PASSWORD=<your-db-password>
                volumes:
                        - ./databaselocal:/var/lib/postgres/data
                networks:
                        - mailsendnetwork

        mailsender:
                container_name: mailsender1
                build: .
                restart: always
                ports:
                        - "8080:8080"

                depends_on:
                        - database
                environment:
                        - POSTGRES_URL=jdbc:postgresql://database:5432/postgres
                        - POSTGRES_USER=postgres
                        - POSTGRES_PASSWORD=<your-db-password>
                        - MAIL_SERVER_ADDR=smtp.gmail.com
                        - MAIL_SERVER_PORT=587
                        - MAIL_USER=<your-mail-addr>
                        - MAIL_PASSWORD=<your-mail-passwd>
                        - MAIL_TARGET_ADDR=<your-target-mail-addr>
                        - LOG_FILE_PATH=/home/mailsender/mailsender.log
                networks:
                        - mailsendnetwork
networks:
        mailsendnetwork: {}
