
spring:
    mail:
        host: ${MAIL_SERVER_ADDR}
        port: ${MAIL_SERVER_PORT}
        username: ${MAIL_USER}
        password: ${MAIL_PASSWORD}
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
    datasource:
        url: ${POSTGRES_URL}
        username: ${POSTGRES_USER}
        password: ${POSTGRES_PASSWORD}
    jpa:
        hibernate:
            ddl-auto: update
        defer-datasource-initialization: true
        properties:
            hibernate:
                jdbc:
                    lob:
                        non_contextual_creation: true

        open-in-view: false

    servlet:
      multipart:
          max-file-size: 20MB
          max-request-size: 20MB

    cache:
        jcache:
            provider: org.ehcache.jsr107.EhcacheCachingProvider
        cache-names:
            - buckets
        caffeine:
            spec: maximumSize=100000,expireAfterAccess=3600s


bucket4j:
    enabled: true
    filters:
        - cache-name: buckets
          http-response-body: "{ \"status\": 429, \"error\": \"Too Many Requests\", \"message\": \"You have exhausted your API Request Quota\" }"
          url: /send*
          rate-limits:
              - expression: getRemoteAddr()
                bandwidths:
                    - capacity: 10
                      time: 1
                      unit: hours


server:
    tomcat:
        max-swallow-size: -1
    ssl:
        key-store: classpath:mycert.p12
        key-store-password: 123456
        keyStoreType: PKCS12


custom:
    mail:
        target: ${MAIL_TARGET_ADDR}

org:
    jobrunr:
      background-job-server:
          enabled: true
      dashboard:
          enabled: true
          port: 8081
# https://awesomeopensource.com/project/MarcGiffing/bucket4j-spring-boot-starter
# https://www.baeldung.com/spring-bucket4j
# https://github.com/MarcGiffing/bucket4j-spring-boot-starter-examples/blob/master/bucket4j-spring-boot-starter-example-caffeine/src/main/resources/application.yml


logging:
    file:
        name: ${LOG_FILE_PATH}
